// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FingerprintProtocol.proto

package serialize

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogicalFingerprint struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogicalFingerprint) Reset()         { *m = LogicalFingerprint{} }
func (m *LogicalFingerprint) String() string { return proto.CompactTextString(m) }
func (*LogicalFingerprint) ProtoMessage()    {}
func (*LogicalFingerprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_98263e7002f8d799, []int{0}
}

func (m *LogicalFingerprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalFingerprint.Unmarshal(m, b)
}
func (m *LogicalFingerprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalFingerprint.Marshal(b, m, deterministic)
}
func (m *LogicalFingerprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalFingerprint.Merge(m, src)
}
func (m *LogicalFingerprint) XXX_Size() int {
	return xxx_messageInfo_LogicalFingerprint.Size(m)
}
func (m *LogicalFingerprint) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalFingerprint.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalFingerprint proto.InternalMessageInfo

func (m *LogicalFingerprint) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type CombinedFingerprints struct {
	Version              *uint32             `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	LocalFingerprint     *LogicalFingerprint `protobuf:"bytes,2,opt,name=localFingerprint" json:"localFingerprint,omitempty"`
	RemoteFingerprint    *LogicalFingerprint `protobuf:"bytes,3,opt,name=remoteFingerprint" json:"remoteFingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CombinedFingerprints) Reset()         { *m = CombinedFingerprints{} }
func (m *CombinedFingerprints) String() string { return proto.CompactTextString(m) }
func (*CombinedFingerprints) ProtoMessage()    {}
func (*CombinedFingerprints) Descriptor() ([]byte, []int) {
	return fileDescriptor_98263e7002f8d799, []int{1}
}

func (m *CombinedFingerprints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombinedFingerprints.Unmarshal(m, b)
}
func (m *CombinedFingerprints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombinedFingerprints.Marshal(b, m, deterministic)
}
func (m *CombinedFingerprints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombinedFingerprints.Merge(m, src)
}
func (m *CombinedFingerprints) XXX_Size() int {
	return xxx_messageInfo_CombinedFingerprints.Size(m)
}
func (m *CombinedFingerprints) XXX_DiscardUnknown() {
	xxx_messageInfo_CombinedFingerprints.DiscardUnknown(m)
}

var xxx_messageInfo_CombinedFingerprints proto.InternalMessageInfo

func (m *CombinedFingerprints) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CombinedFingerprints) GetLocalFingerprint() *LogicalFingerprint {
	if m != nil {
		return m.LocalFingerprint
	}
	return nil
}

func (m *CombinedFingerprints) GetRemoteFingerprint() *LogicalFingerprint {
	if m != nil {
		return m.RemoteFingerprint
	}
	return nil
}

func init() {
	proto.RegisterType((*LogicalFingerprint)(nil), "serialize.LogicalFingerprint")
	proto.RegisterType((*CombinedFingerprints)(nil), "serialize.CombinedFingerprints")
}

func init() { proto.RegisterFile("FingerprintProtocol.proto", fileDescriptor_98263e7002f8d799) }

var fileDescriptor_98263e7002f8d799 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x74, 0xcb, 0xcc, 0x4b,
	0x4f, 0x2d, 0x2a, 0x28, 0xca, 0xcc, 0x2b, 0x09, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1,
	0x2b, 0x00, 0x31, 0x84, 0x38, 0x8b, 0x53, 0x8b, 0x32, 0x13, 0x73, 0x32, 0xab, 0x52, 0x95, 0xf4,
	0xb8, 0x84, 0x7c, 0xf2, 0xd3, 0x33, 0x93, 0x13, 0x73, 0x90, 0x94, 0x0b, 0x49, 0x70, 0xb1, 0x27,
	0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0xc1, 0xb8, 0x4a,
	0x27, 0x18, 0xb9, 0x44, 0x9c, 0xf3, 0x73, 0x93, 0x32, 0xf3, 0x52, 0x53, 0x90, 0x74, 0x14, 0x83,
	0xb4, 0x94, 0xa5, 0x16, 0x15, 0x67, 0xe6, 0xe7, 0x81, 0xb5, 0xf0, 0x06, 0xc1, 0xb8, 0x42, 0x9e,
	0x5c, 0x02, 0x39, 0xf9, 0xa8, 0x16, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0xc9, 0xea, 0xc1,
	0x1d, 0xa2, 0x87, 0xe9, 0x8a, 0x20, 0x0c, 0x6d, 0x42, 0xde, 0x5c, 0x82, 0x45, 0xa9, 0xb9, 0xf9,
	0x25, 0xa9, 0xc8, 0x66, 0x31, 0x13, 0x63, 0x16, 0xa6, 0x3e, 0x27, 0x5b, 0x2e, 0x8d, 0xfc, 0xa2,
	0x74, 0xbd, 0xf2, 0x8c, 0xcc, 0xe2, 0x82, 0xd4, 0xa2, 0xe2, 0xca, 0xe2, 0x92, 0xd4, 0xdc, 0x62,
	0xbd, 0x9c, 0xcc, 0xa4, 0xe2, 0xcc, 0xf4, 0xbc, 0xc4, 0x1c, 0xbd, 0x34, 0x24, 0xb5, 0x82, 0xe8,
	0x81, 0x59, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x98, 0x79, 0x86, 0x60, 0x01, 0x00, 0x00,
}
