// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LocalStorageProtocol.proto

package serialize

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionStructure struct {
	SessionVersion       *uint32                              `protobuf:"varint,1,opt,name=sessionVersion" json:"sessionVersion,omitempty"`
	LocalIdentityPublic  []byte                               `protobuf:"bytes,2,opt,name=localIdentityPublic" json:"localIdentityPublic,omitempty"`
	RemoteIdentityPublic []byte                               `protobuf:"bytes,3,opt,name=remoteIdentityPublic" json:"remoteIdentityPublic,omitempty"`
	RootKey              []byte                               `protobuf:"bytes,4,opt,name=rootKey" json:"rootKey,omitempty"`
	PreviousCounter      *uint32                              `protobuf:"varint,5,opt,name=previousCounter" json:"previousCounter,omitempty"`
	SenderChain          *SessionStructure_Chain              `protobuf:"bytes,6,opt,name=senderChain" json:"senderChain,omitempty"`
	ReceiverChains       []*SessionStructure_Chain            `protobuf:"bytes,7,rep,name=receiverChains" json:"receiverChains,omitempty"`
	PendingKeyExchange   *SessionStructure_PendingKeyExchange `protobuf:"bytes,8,opt,name=pendingKeyExchange" json:"pendingKeyExchange,omitempty"`
	PendingPreKey        *SessionStructure_PendingPreKey      `protobuf:"bytes,9,opt,name=pendingPreKey" json:"pendingPreKey,omitempty"`
	RemoteRegistrationId *uint32                              `protobuf:"varint,10,opt,name=remoteRegistrationId" json:"remoteRegistrationId,omitempty"`
	LocalRegistrationId  *uint32                              `protobuf:"varint,11,opt,name=localRegistrationId" json:"localRegistrationId,omitempty"`
	NeedsRefresh         *bool                                `protobuf:"varint,12,opt,name=needsRefresh" json:"needsRefresh,omitempty"`
	AliceBaseKey         []byte                               `protobuf:"bytes,13,opt,name=aliceBaseKey" json:"aliceBaseKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *SessionStructure) Reset()         { *m = SessionStructure{} }
func (m *SessionStructure) String() string { return proto.CompactTextString(m) }
func (*SessionStructure) ProtoMessage()    {}
func (*SessionStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{0}
}

func (m *SessionStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStructure.Unmarshal(m, b)
}
func (m *SessionStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStructure.Marshal(b, m, deterministic)
}
func (m *SessionStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStructure.Merge(m, src)
}
func (m *SessionStructure) XXX_Size() int {
	return xxx_messageInfo_SessionStructure.Size(m)
}
func (m *SessionStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStructure.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStructure proto.InternalMessageInfo

func (m *SessionStructure) GetSessionVersion() uint32 {
	if m != nil && m.SessionVersion != nil {
		return *m.SessionVersion
	}
	return 0
}

func (m *SessionStructure) GetLocalIdentityPublic() []byte {
	if m != nil {
		return m.LocalIdentityPublic
	}
	return nil
}

func (m *SessionStructure) GetRemoteIdentityPublic() []byte {
	if m != nil {
		return m.RemoteIdentityPublic
	}
	return nil
}

func (m *SessionStructure) GetRootKey() []byte {
	if m != nil {
		return m.RootKey
	}
	return nil
}

func (m *SessionStructure) GetPreviousCounter() uint32 {
	if m != nil && m.PreviousCounter != nil {
		return *m.PreviousCounter
	}
	return 0
}

func (m *SessionStructure) GetSenderChain() *SessionStructure_Chain {
	if m != nil {
		return m.SenderChain
	}
	return nil
}

func (m *SessionStructure) GetReceiverChains() []*SessionStructure_Chain {
	if m != nil {
		return m.ReceiverChains
	}
	return nil
}

func (m *SessionStructure) GetPendingKeyExchange() *SessionStructure_PendingKeyExchange {
	if m != nil {
		return m.PendingKeyExchange
	}
	return nil
}

func (m *SessionStructure) GetPendingPreKey() *SessionStructure_PendingPreKey {
	if m != nil {
		return m.PendingPreKey
	}
	return nil
}

func (m *SessionStructure) GetRemoteRegistrationId() uint32 {
	if m != nil && m.RemoteRegistrationId != nil {
		return *m.RemoteRegistrationId
	}
	return 0
}

func (m *SessionStructure) GetLocalRegistrationId() uint32 {
	if m != nil && m.LocalRegistrationId != nil {
		return *m.LocalRegistrationId
	}
	return 0
}

func (m *SessionStructure) GetNeedsRefresh() bool {
	if m != nil && m.NeedsRefresh != nil {
		return *m.NeedsRefresh
	}
	return false
}

func (m *SessionStructure) GetAliceBaseKey() []byte {
	if m != nil {
		return m.AliceBaseKey
	}
	return nil
}

type SessionStructure_Chain struct {
	SenderRatchetKey        []byte                               `protobuf:"bytes,1,opt,name=senderRatchetKey" json:"senderRatchetKey,omitempty"`
	SenderRatchetKeyPrivate []byte                               `protobuf:"bytes,2,opt,name=senderRatchetKeyPrivate" json:"senderRatchetKeyPrivate,omitempty"`
	ChainKey                *SessionStructure_Chain_ChainKey     `protobuf:"bytes,3,opt,name=chainKey" json:"chainKey,omitempty"`
	MessageKeys             []*SessionStructure_Chain_MessageKey `protobuf:"bytes,4,rep,name=messageKeys" json:"messageKeys,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                             `json:"-"`
	XXX_unrecognized        []byte                               `json:"-"`
	XXX_sizecache           int32                                `json:"-"`
}

func (m *SessionStructure_Chain) Reset()         { *m = SessionStructure_Chain{} }
func (m *SessionStructure_Chain) String() string { return proto.CompactTextString(m) }
func (*SessionStructure_Chain) ProtoMessage()    {}
func (*SessionStructure_Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{0, 0}
}

func (m *SessionStructure_Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStructure_Chain.Unmarshal(m, b)
}
func (m *SessionStructure_Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStructure_Chain.Marshal(b, m, deterministic)
}
func (m *SessionStructure_Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStructure_Chain.Merge(m, src)
}
func (m *SessionStructure_Chain) XXX_Size() int {
	return xxx_messageInfo_SessionStructure_Chain.Size(m)
}
func (m *SessionStructure_Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStructure_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStructure_Chain proto.InternalMessageInfo

func (m *SessionStructure_Chain) GetSenderRatchetKey() []byte {
	if m != nil {
		return m.SenderRatchetKey
	}
	return nil
}

func (m *SessionStructure_Chain) GetSenderRatchetKeyPrivate() []byte {
	if m != nil {
		return m.SenderRatchetKeyPrivate
	}
	return nil
}

func (m *SessionStructure_Chain) GetChainKey() *SessionStructure_Chain_ChainKey {
	if m != nil {
		return m.ChainKey
	}
	return nil
}

func (m *SessionStructure_Chain) GetMessageKeys() []*SessionStructure_Chain_MessageKey {
	if m != nil {
		return m.MessageKeys
	}
	return nil
}

type SessionStructure_Chain_ChainKey struct {
	Index                *uint32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStructure_Chain_ChainKey) Reset()         { *m = SessionStructure_Chain_ChainKey{} }
func (m *SessionStructure_Chain_ChainKey) String() string { return proto.CompactTextString(m) }
func (*SessionStructure_Chain_ChainKey) ProtoMessage()    {}
func (*SessionStructure_Chain_ChainKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{0, 0, 0}
}

func (m *SessionStructure_Chain_ChainKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStructure_Chain_ChainKey.Unmarshal(m, b)
}
func (m *SessionStructure_Chain_ChainKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStructure_Chain_ChainKey.Marshal(b, m, deterministic)
}
func (m *SessionStructure_Chain_ChainKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStructure_Chain_ChainKey.Merge(m, src)
}
func (m *SessionStructure_Chain_ChainKey) XXX_Size() int {
	return xxx_messageInfo_SessionStructure_Chain_ChainKey.Size(m)
}
func (m *SessionStructure_Chain_ChainKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStructure_Chain_ChainKey.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStructure_Chain_ChainKey proto.InternalMessageInfo

func (m *SessionStructure_Chain_ChainKey) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *SessionStructure_Chain_ChainKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type SessionStructure_Chain_MessageKey struct {
	Index                *uint32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	CipherKey            []byte   `protobuf:"bytes,2,opt,name=cipherKey" json:"cipherKey,omitempty"`
	MacKey               []byte   `protobuf:"bytes,3,opt,name=macKey" json:"macKey,omitempty"`
	Iv                   []byte   `protobuf:"bytes,4,opt,name=iv" json:"iv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStructure_Chain_MessageKey) Reset()         { *m = SessionStructure_Chain_MessageKey{} }
func (m *SessionStructure_Chain_MessageKey) String() string { return proto.CompactTextString(m) }
func (*SessionStructure_Chain_MessageKey) ProtoMessage()    {}
func (*SessionStructure_Chain_MessageKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{0, 0, 1}
}

func (m *SessionStructure_Chain_MessageKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStructure_Chain_MessageKey.Unmarshal(m, b)
}
func (m *SessionStructure_Chain_MessageKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStructure_Chain_MessageKey.Marshal(b, m, deterministic)
}
func (m *SessionStructure_Chain_MessageKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStructure_Chain_MessageKey.Merge(m, src)
}
func (m *SessionStructure_Chain_MessageKey) XXX_Size() int {
	return xxx_messageInfo_SessionStructure_Chain_MessageKey.Size(m)
}
func (m *SessionStructure_Chain_MessageKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStructure_Chain_MessageKey.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStructure_Chain_MessageKey proto.InternalMessageInfo

func (m *SessionStructure_Chain_MessageKey) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *SessionStructure_Chain_MessageKey) GetCipherKey() []byte {
	if m != nil {
		return m.CipherKey
	}
	return nil
}

func (m *SessionStructure_Chain_MessageKey) GetMacKey() []byte {
	if m != nil {
		return m.MacKey
	}
	return nil
}

func (m *SessionStructure_Chain_MessageKey) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

type SessionStructure_PendingKeyExchange struct {
	Sequence                *uint32  `protobuf:"varint,1,opt,name=sequence" json:"sequence,omitempty"`
	LocalBaseKey            []byte   `protobuf:"bytes,2,opt,name=localBaseKey" json:"localBaseKey,omitempty"`
	LocalBaseKeyPrivate     []byte   `protobuf:"bytes,3,opt,name=localBaseKeyPrivate" json:"localBaseKeyPrivate,omitempty"`
	LocalRatchetKey         []byte   `protobuf:"bytes,4,opt,name=localRatchetKey" json:"localRatchetKey,omitempty"`
	LocalRatchetKeyPrivate  []byte   `protobuf:"bytes,5,opt,name=localRatchetKeyPrivate" json:"localRatchetKeyPrivate,omitempty"`
	LocalIdentityKey        []byte   `protobuf:"bytes,7,opt,name=localIdentityKey" json:"localIdentityKey,omitempty"`
	LocalIdentityKeyPrivate []byte   `protobuf:"bytes,8,opt,name=localIdentityKeyPrivate" json:"localIdentityKeyPrivate,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SessionStructure_PendingKeyExchange) Reset()         { *m = SessionStructure_PendingKeyExchange{} }
func (m *SessionStructure_PendingKeyExchange) String() string { return proto.CompactTextString(m) }
func (*SessionStructure_PendingKeyExchange) ProtoMessage()    {}
func (*SessionStructure_PendingKeyExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{0, 1}
}

func (m *SessionStructure_PendingKeyExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStructure_PendingKeyExchange.Unmarshal(m, b)
}
func (m *SessionStructure_PendingKeyExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStructure_PendingKeyExchange.Marshal(b, m, deterministic)
}
func (m *SessionStructure_PendingKeyExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStructure_PendingKeyExchange.Merge(m, src)
}
func (m *SessionStructure_PendingKeyExchange) XXX_Size() int {
	return xxx_messageInfo_SessionStructure_PendingKeyExchange.Size(m)
}
func (m *SessionStructure_PendingKeyExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStructure_PendingKeyExchange.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStructure_PendingKeyExchange proto.InternalMessageInfo

func (m *SessionStructure_PendingKeyExchange) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *SessionStructure_PendingKeyExchange) GetLocalBaseKey() []byte {
	if m != nil {
		return m.LocalBaseKey
	}
	return nil
}

func (m *SessionStructure_PendingKeyExchange) GetLocalBaseKeyPrivate() []byte {
	if m != nil {
		return m.LocalBaseKeyPrivate
	}
	return nil
}

func (m *SessionStructure_PendingKeyExchange) GetLocalRatchetKey() []byte {
	if m != nil {
		return m.LocalRatchetKey
	}
	return nil
}

func (m *SessionStructure_PendingKeyExchange) GetLocalRatchetKeyPrivate() []byte {
	if m != nil {
		return m.LocalRatchetKeyPrivate
	}
	return nil
}

func (m *SessionStructure_PendingKeyExchange) GetLocalIdentityKey() []byte {
	if m != nil {
		return m.LocalIdentityKey
	}
	return nil
}

func (m *SessionStructure_PendingKeyExchange) GetLocalIdentityKeyPrivate() []byte {
	if m != nil {
		return m.LocalIdentityKeyPrivate
	}
	return nil
}

type SessionStructure_PendingPreKey struct {
	PreKeyId             *uint32  `protobuf:"varint,1,opt,name=preKeyId" json:"preKeyId,omitempty"`
	SignedPreKeyId       *int32   `protobuf:"varint,3,opt,name=signedPreKeyId" json:"signedPreKeyId,omitempty"`
	BaseKey              []byte   `protobuf:"bytes,2,opt,name=baseKey" json:"baseKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStructure_PendingPreKey) Reset()         { *m = SessionStructure_PendingPreKey{} }
func (m *SessionStructure_PendingPreKey) String() string { return proto.CompactTextString(m) }
func (*SessionStructure_PendingPreKey) ProtoMessage()    {}
func (*SessionStructure_PendingPreKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{0, 2}
}

func (m *SessionStructure_PendingPreKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStructure_PendingPreKey.Unmarshal(m, b)
}
func (m *SessionStructure_PendingPreKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStructure_PendingPreKey.Marshal(b, m, deterministic)
}
func (m *SessionStructure_PendingPreKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStructure_PendingPreKey.Merge(m, src)
}
func (m *SessionStructure_PendingPreKey) XXX_Size() int {
	return xxx_messageInfo_SessionStructure_PendingPreKey.Size(m)
}
func (m *SessionStructure_PendingPreKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStructure_PendingPreKey.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStructure_PendingPreKey proto.InternalMessageInfo

func (m *SessionStructure_PendingPreKey) GetPreKeyId() uint32 {
	if m != nil && m.PreKeyId != nil {
		return *m.PreKeyId
	}
	return 0
}

func (m *SessionStructure_PendingPreKey) GetSignedPreKeyId() int32 {
	if m != nil && m.SignedPreKeyId != nil {
		return *m.SignedPreKeyId
	}
	return 0
}

func (m *SessionStructure_PendingPreKey) GetBaseKey() []byte {
	if m != nil {
		return m.BaseKey
	}
	return nil
}

type RecordStructure struct {
	CurrentSession       *SessionStructure   `protobuf:"bytes,1,opt,name=currentSession" json:"currentSession,omitempty"`
	PreviousSessions     []*SessionStructure `protobuf:"bytes,2,rep,name=previousSessions" json:"previousSessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RecordStructure) Reset()         { *m = RecordStructure{} }
func (m *RecordStructure) String() string { return proto.CompactTextString(m) }
func (*RecordStructure) ProtoMessage()    {}
func (*RecordStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{1}
}

func (m *RecordStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordStructure.Unmarshal(m, b)
}
func (m *RecordStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordStructure.Marshal(b, m, deterministic)
}
func (m *RecordStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordStructure.Merge(m, src)
}
func (m *RecordStructure) XXX_Size() int {
	return xxx_messageInfo_RecordStructure.Size(m)
}
func (m *RecordStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordStructure.DiscardUnknown(m)
}

var xxx_messageInfo_RecordStructure proto.InternalMessageInfo

func (m *RecordStructure) GetCurrentSession() *SessionStructure {
	if m != nil {
		return m.CurrentSession
	}
	return nil
}

func (m *RecordStructure) GetPreviousSessions() []*SessionStructure {
	if m != nil {
		return m.PreviousSessions
	}
	return nil
}

type PreKeyRecordStructure struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey" json:"publicKey,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,3,opt,name=privateKey" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreKeyRecordStructure) Reset()         { *m = PreKeyRecordStructure{} }
func (m *PreKeyRecordStructure) String() string { return proto.CompactTextString(m) }
func (*PreKeyRecordStructure) ProtoMessage()    {}
func (*PreKeyRecordStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{2}
}

func (m *PreKeyRecordStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreKeyRecordStructure.Unmarshal(m, b)
}
func (m *PreKeyRecordStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreKeyRecordStructure.Marshal(b, m, deterministic)
}
func (m *PreKeyRecordStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreKeyRecordStructure.Merge(m, src)
}
func (m *PreKeyRecordStructure) XXX_Size() int {
	return xxx_messageInfo_PreKeyRecordStructure.Size(m)
}
func (m *PreKeyRecordStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_PreKeyRecordStructure.DiscardUnknown(m)
}

var xxx_messageInfo_PreKeyRecordStructure proto.InternalMessageInfo

func (m *PreKeyRecordStructure) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PreKeyRecordStructure) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PreKeyRecordStructure) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type SignedPreKeyRecordStructure struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey" json:"publicKey,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,3,opt,name=privateKey" json:"privateKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	Timestamp            *uint64  `protobuf:"fixed64,5,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedPreKeyRecordStructure) Reset()         { *m = SignedPreKeyRecordStructure{} }
func (m *SignedPreKeyRecordStructure) String() string { return proto.CompactTextString(m) }
func (*SignedPreKeyRecordStructure) ProtoMessage()    {}
func (*SignedPreKeyRecordStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{3}
}

func (m *SignedPreKeyRecordStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedPreKeyRecordStructure.Unmarshal(m, b)
}
func (m *SignedPreKeyRecordStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedPreKeyRecordStructure.Marshal(b, m, deterministic)
}
func (m *SignedPreKeyRecordStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedPreKeyRecordStructure.Merge(m, src)
}
func (m *SignedPreKeyRecordStructure) XXX_Size() int {
	return xxx_messageInfo_SignedPreKeyRecordStructure.Size(m)
}
func (m *SignedPreKeyRecordStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedPreKeyRecordStructure.DiscardUnknown(m)
}

var xxx_messageInfo_SignedPreKeyRecordStructure proto.InternalMessageInfo

func (m *SignedPreKeyRecordStructure) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SignedPreKeyRecordStructure) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *SignedPreKeyRecordStructure) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *SignedPreKeyRecordStructure) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedPreKeyRecordStructure) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type IdentityKeyPairStructure struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey" json:"publicKey,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,2,opt,name=privateKey" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityKeyPairStructure) Reset()         { *m = IdentityKeyPairStructure{} }
func (m *IdentityKeyPairStructure) String() string { return proto.CompactTextString(m) }
func (*IdentityKeyPairStructure) ProtoMessage()    {}
func (*IdentityKeyPairStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{4}
}

func (m *IdentityKeyPairStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityKeyPairStructure.Unmarshal(m, b)
}
func (m *IdentityKeyPairStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityKeyPairStructure.Marshal(b, m, deterministic)
}
func (m *IdentityKeyPairStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityKeyPairStructure.Merge(m, src)
}
func (m *IdentityKeyPairStructure) XXX_Size() int {
	return xxx_messageInfo_IdentityKeyPairStructure.Size(m)
}
func (m *IdentityKeyPairStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityKeyPairStructure.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityKeyPairStructure proto.InternalMessageInfo

func (m *IdentityKeyPairStructure) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *IdentityKeyPairStructure) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type SenderKeyStateStructure struct {
	SenderKeyId          *uint32                                     `protobuf:"varint,1,opt,name=senderKeyId" json:"senderKeyId,omitempty"`
	SenderChainKey       *SenderKeyStateStructure_SenderChainKey     `protobuf:"bytes,2,opt,name=senderChainKey" json:"senderChainKey,omitempty"`
	SenderSigningKey     *SenderKeyStateStructure_SenderSigningKey   `protobuf:"bytes,3,opt,name=senderSigningKey" json:"senderSigningKey,omitempty"`
	SenderMessageKeys    []*SenderKeyStateStructure_SenderMessageKey `protobuf:"bytes,4,rep,name=senderMessageKeys" json:"senderMessageKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *SenderKeyStateStructure) Reset()         { *m = SenderKeyStateStructure{} }
func (m *SenderKeyStateStructure) String() string { return proto.CompactTextString(m) }
func (*SenderKeyStateStructure) ProtoMessage()    {}
func (*SenderKeyStateStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{5}
}

func (m *SenderKeyStateStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderKeyStateStructure.Unmarshal(m, b)
}
func (m *SenderKeyStateStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderKeyStateStructure.Marshal(b, m, deterministic)
}
func (m *SenderKeyStateStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderKeyStateStructure.Merge(m, src)
}
func (m *SenderKeyStateStructure) XXX_Size() int {
	return xxx_messageInfo_SenderKeyStateStructure.Size(m)
}
func (m *SenderKeyStateStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderKeyStateStructure.DiscardUnknown(m)
}

var xxx_messageInfo_SenderKeyStateStructure proto.InternalMessageInfo

func (m *SenderKeyStateStructure) GetSenderKeyId() uint32 {
	if m != nil && m.SenderKeyId != nil {
		return *m.SenderKeyId
	}
	return 0
}

func (m *SenderKeyStateStructure) GetSenderChainKey() *SenderKeyStateStructure_SenderChainKey {
	if m != nil {
		return m.SenderChainKey
	}
	return nil
}

func (m *SenderKeyStateStructure) GetSenderSigningKey() *SenderKeyStateStructure_SenderSigningKey {
	if m != nil {
		return m.SenderSigningKey
	}
	return nil
}

func (m *SenderKeyStateStructure) GetSenderMessageKeys() []*SenderKeyStateStructure_SenderMessageKey {
	if m != nil {
		return m.SenderMessageKeys
	}
	return nil
}

type SenderKeyStateStructure_SenderChainKey struct {
	Iteration            *uint32  `protobuf:"varint,1,opt,name=iteration" json:"iteration,omitempty"`
	Seed                 []byte   `protobuf:"bytes,2,opt,name=seed" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SenderKeyStateStructure_SenderChainKey) Reset() {
	*m = SenderKeyStateStructure_SenderChainKey{}
}
func (m *SenderKeyStateStructure_SenderChainKey) String() string { return proto.CompactTextString(m) }
func (*SenderKeyStateStructure_SenderChainKey) ProtoMessage()    {}
func (*SenderKeyStateStructure_SenderChainKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{5, 0}
}

func (m *SenderKeyStateStructure_SenderChainKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderKeyStateStructure_SenderChainKey.Unmarshal(m, b)
}
func (m *SenderKeyStateStructure_SenderChainKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderKeyStateStructure_SenderChainKey.Marshal(b, m, deterministic)
}
func (m *SenderKeyStateStructure_SenderChainKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderKeyStateStructure_SenderChainKey.Merge(m, src)
}
func (m *SenderKeyStateStructure_SenderChainKey) XXX_Size() int {
	return xxx_messageInfo_SenderKeyStateStructure_SenderChainKey.Size(m)
}
func (m *SenderKeyStateStructure_SenderChainKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderKeyStateStructure_SenderChainKey.DiscardUnknown(m)
}

var xxx_messageInfo_SenderKeyStateStructure_SenderChainKey proto.InternalMessageInfo

func (m *SenderKeyStateStructure_SenderChainKey) GetIteration() uint32 {
	if m != nil && m.Iteration != nil {
		return *m.Iteration
	}
	return 0
}

func (m *SenderKeyStateStructure_SenderChainKey) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type SenderKeyStateStructure_SenderMessageKey struct {
	Iteration            *uint32  `protobuf:"varint,1,opt,name=iteration" json:"iteration,omitempty"`
	Seed                 []byte   `protobuf:"bytes,2,opt,name=seed" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SenderKeyStateStructure_SenderMessageKey) Reset() {
	*m = SenderKeyStateStructure_SenderMessageKey{}
}
func (m *SenderKeyStateStructure_SenderMessageKey) String() string { return proto.CompactTextString(m) }
func (*SenderKeyStateStructure_SenderMessageKey) ProtoMessage()    {}
func (*SenderKeyStateStructure_SenderMessageKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{5, 1}
}

func (m *SenderKeyStateStructure_SenderMessageKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderKeyStateStructure_SenderMessageKey.Unmarshal(m, b)
}
func (m *SenderKeyStateStructure_SenderMessageKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderKeyStateStructure_SenderMessageKey.Marshal(b, m, deterministic)
}
func (m *SenderKeyStateStructure_SenderMessageKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderKeyStateStructure_SenderMessageKey.Merge(m, src)
}
func (m *SenderKeyStateStructure_SenderMessageKey) XXX_Size() int {
	return xxx_messageInfo_SenderKeyStateStructure_SenderMessageKey.Size(m)
}
func (m *SenderKeyStateStructure_SenderMessageKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderKeyStateStructure_SenderMessageKey.DiscardUnknown(m)
}

var xxx_messageInfo_SenderKeyStateStructure_SenderMessageKey proto.InternalMessageInfo

func (m *SenderKeyStateStructure_SenderMessageKey) GetIteration() uint32 {
	if m != nil && m.Iteration != nil {
		return *m.Iteration
	}
	return 0
}

func (m *SenderKeyStateStructure_SenderMessageKey) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type SenderKeyStateStructure_SenderSigningKey struct {
	Public               []byte   `protobuf:"bytes,1,opt,name=public" json:"public,omitempty"`
	Private              []byte   `protobuf:"bytes,2,opt,name=private" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SenderKeyStateStructure_SenderSigningKey) Reset() {
	*m = SenderKeyStateStructure_SenderSigningKey{}
}
func (m *SenderKeyStateStructure_SenderSigningKey) String() string { return proto.CompactTextString(m) }
func (*SenderKeyStateStructure_SenderSigningKey) ProtoMessage()    {}
func (*SenderKeyStateStructure_SenderSigningKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{5, 2}
}

func (m *SenderKeyStateStructure_SenderSigningKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderKeyStateStructure_SenderSigningKey.Unmarshal(m, b)
}
func (m *SenderKeyStateStructure_SenderSigningKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderKeyStateStructure_SenderSigningKey.Marshal(b, m, deterministic)
}
func (m *SenderKeyStateStructure_SenderSigningKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderKeyStateStructure_SenderSigningKey.Merge(m, src)
}
func (m *SenderKeyStateStructure_SenderSigningKey) XXX_Size() int {
	return xxx_messageInfo_SenderKeyStateStructure_SenderSigningKey.Size(m)
}
func (m *SenderKeyStateStructure_SenderSigningKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderKeyStateStructure_SenderSigningKey.DiscardUnknown(m)
}

var xxx_messageInfo_SenderKeyStateStructure_SenderSigningKey proto.InternalMessageInfo

func (m *SenderKeyStateStructure_SenderSigningKey) GetPublic() []byte {
	if m != nil {
		return m.Public
	}
	return nil
}

func (m *SenderKeyStateStructure_SenderSigningKey) GetPrivate() []byte {
	if m != nil {
		return m.Private
	}
	return nil
}

type SenderKeyRecordStructure struct {
	SenderKeyStates      []*SenderKeyStateStructure `protobuf:"bytes,1,rep,name=senderKeyStates" json:"senderKeyStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SenderKeyRecordStructure) Reset()         { *m = SenderKeyRecordStructure{} }
func (m *SenderKeyRecordStructure) String() string { return proto.CompactTextString(m) }
func (*SenderKeyRecordStructure) ProtoMessage()    {}
func (*SenderKeyRecordStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e237dd9d1a4dbd, []int{6}
}

func (m *SenderKeyRecordStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderKeyRecordStructure.Unmarshal(m, b)
}
func (m *SenderKeyRecordStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderKeyRecordStructure.Marshal(b, m, deterministic)
}
func (m *SenderKeyRecordStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderKeyRecordStructure.Merge(m, src)
}
func (m *SenderKeyRecordStructure) XXX_Size() int {
	return xxx_messageInfo_SenderKeyRecordStructure.Size(m)
}
func (m *SenderKeyRecordStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderKeyRecordStructure.DiscardUnknown(m)
}

var xxx_messageInfo_SenderKeyRecordStructure proto.InternalMessageInfo

func (m *SenderKeyRecordStructure) GetSenderKeyStates() []*SenderKeyStateStructure {
	if m != nil {
		return m.SenderKeyStates
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionStructure)(nil), "serialize.SessionStructure")
	proto.RegisterType((*SessionStructure_Chain)(nil), "serialize.SessionStructure.Chain")
	proto.RegisterType((*SessionStructure_Chain_ChainKey)(nil), "serialize.SessionStructure.Chain.ChainKey")
	proto.RegisterType((*SessionStructure_Chain_MessageKey)(nil), "serialize.SessionStructure.Chain.MessageKey")
	proto.RegisterType((*SessionStructure_PendingKeyExchange)(nil), "serialize.SessionStructure.PendingKeyExchange")
	proto.RegisterType((*SessionStructure_PendingPreKey)(nil), "serialize.SessionStructure.PendingPreKey")
	proto.RegisterType((*RecordStructure)(nil), "serialize.RecordStructure")
	proto.RegisterType((*PreKeyRecordStructure)(nil), "serialize.PreKeyRecordStructure")
	proto.RegisterType((*SignedPreKeyRecordStructure)(nil), "serialize.SignedPreKeyRecordStructure")
	proto.RegisterType((*IdentityKeyPairStructure)(nil), "serialize.IdentityKeyPairStructure")
	proto.RegisterType((*SenderKeyStateStructure)(nil), "serialize.SenderKeyStateStructure")
	proto.RegisterType((*SenderKeyStateStructure_SenderChainKey)(nil), "serialize.SenderKeyStateStructure.SenderChainKey")
	proto.RegisterType((*SenderKeyStateStructure_SenderMessageKey)(nil), "serialize.SenderKeyStateStructure.SenderMessageKey")
	proto.RegisterType((*SenderKeyStateStructure_SenderSigningKey)(nil), "serialize.SenderKeyStateStructure.SenderSigningKey")
	proto.RegisterType((*SenderKeyRecordStructure)(nil), "serialize.SenderKeyRecordStructure")
}

func init() { proto.RegisterFile("LocalStorageProtocol.proto", fileDescriptor_98e237dd9d1a4dbd) }

var fileDescriptor_98e237dd9d1a4dbd = []byte{
	// 950 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdb, 0x8e, 0xeb, 0x34,
	0x14, 0x55, 0xda, 0xe9, 0x4c, 0x67, 0xf7, 0x32, 0x83, 0x39, 0xcc, 0x89, 0x72, 0x10, 0x2a, 0x79,
	0x40, 0xe5, 0x08, 0x55, 0xd0, 0x23, 0x21, 0x9e, 0x67, 0xb8, 0x68, 0x34, 0xe7, 0x40, 0x95, 0x4a,
	0x08, 0x5e, 0x40, 0x9e, 0x64, 0xd3, 0x5a, 0xb4, 0x49, 0xb0, 0xdd, 0x32, 0xe5, 0x67, 0x78, 0xe0,
	0x01, 0x89, 0x3f, 0xe0, 0x27, 0xf8, 0x26, 0x64, 0xc7, 0xce, 0xc5, 0xed, 0x5c, 0x24, 0xc4, 0x4b,
	0x1b, 0x2f, 0x7b, 0xaf, 0xed, 0xac, 0xbd, 0xbc, 0x1d, 0x08, 0x5e, 0x67, 0x31, 0x5d, 0xcd, 0x65,
	0xc6, 0xe9, 0x02, 0x67, 0x3c, 0x93, 0x59, 0x9c, 0xad, 0x26, 0xb9, 0x7a, 0x20, 0xa7, 0x02, 0x39,
	0xa3, 0x2b, 0xf6, 0x1b, 0x86, 0x7f, 0xf7, 0xe1, 0x7c, 0x8e, 0x42, 0xb0, 0x2c, 0x9d, 0x4b, 0xbe,
	0x89, 0xe5, 0x86, 0x23, 0xf9, 0x00, 0x86, 0xa2, 0xc0, 0xbe, 0x45, 0xae, 0xfe, 0x7c, 0x6f, 0xe4,
	0x8d, 0x07, 0x91, 0x83, 0x92, 0x8f, 0xe1, 0xed, 0x95, 0xca, 0x72, 0x9d, 0x60, 0x2a, 0x99, 0xdc,
	0xcd, 0x36, 0xb7, 0x2b, 0x16, 0xfb, 0xad, 0x91, 0x37, 0xee, 0x47, 0x87, 0xa6, 0xc8, 0x14, 0x9e,
	0x71, 0x5c, 0x67, 0x12, 0x9d, 0x90, 0xb6, 0x0e, 0x39, 0x38, 0x47, 0x7c, 0x38, 0xe1, 0x59, 0x26,
	0x6f, 0x70, 0xe7, 0x1f, 0xe9, 0x65, 0x76, 0x48, 0xc6, 0x70, 0x96, 0x73, 0xdc, 0xb2, 0x6c, 0x23,
	0xae, 0xb2, 0x4d, 0x2a, 0x91, 0xfb, 0x1d, 0xbd, 0x51, 0x17, 0x26, 0x57, 0xd0, 0x13, 0x98, 0x26,
	0xc8, 0xaf, 0x96, 0x94, 0xa5, 0xfe, 0xf1, 0xc8, 0x1b, 0xf7, 0xa6, 0xef, 0x4f, 0x4a, 0x1d, 0x26,
	0xae, 0x06, 0x13, 0xbd, 0x30, 0xaa, 0x47, 0x91, 0x6b, 0x18, 0x72, 0x8c, 0x91, 0x6d, 0x0d, 0x20,
	0xfc, 0x93, 0x51, 0xfb, 0x69, 0x3c, 0x4e, 0x20, 0xf9, 0x01, 0x48, 0x8e, 0x69, 0xc2, 0xd2, 0xc5,
	0x0d, 0xee, 0xbe, 0xb8, 0x8b, 0x97, 0x34, 0x5d, 0xa0, 0xdf, 0xd5, 0xdb, 0x9a, 0x3c, 0x44, 0x37,
	0xdb, 0x8b, 0x8a, 0x0e, 0x30, 0x91, 0x6f, 0x60, 0x60, 0xd0, 0x19, 0x47, 0xa5, 0xdc, 0xa9, 0xa6,
	0xfe, 0xf0, 0x09, 0xd4, 0x45, 0x40, 0xd4, 0x8c, 0xaf, 0x0a, 0x17, 0xe1, 0x82, 0x09, 0xc9, 0xa9,
	0x64, 0x59, 0x7a, 0x9d, 0xf8, 0xa0, 0xf5, 0x3e, 0x38, 0x57, 0xda, 0xc3, 0x09, 0xe9, 0xe9, 0x90,
	0x43, 0x53, 0x24, 0x84, 0x7e, 0x8a, 0x98, 0x88, 0x08, 0x7f, 0xe2, 0x28, 0x96, 0x7e, 0x7f, 0xe4,
	0x8d, 0xbb, 0x51, 0x03, 0x53, 0x6b, 0xe8, 0x8a, 0xc5, 0x78, 0x49, 0x85, 0x7e, 0xb3, 0x81, 0xf6,
	0x44, 0x03, 0x0b, 0xfe, 0x68, 0x43, 0xa7, 0xa8, 0xd9, 0x4b, 0x38, 0x2f, 0x4a, 0x18, 0x51, 0x19,
	0x2f, 0x51, 0xbb, 0xc8, 0xd3, 0x11, 0x7b, 0x38, 0xf9, 0x0c, 0x9e, 0xbb, 0xd8, 0x8c, 0xb3, 0x2d,
	0x95, 0x68, 0x2c, 0x7d, 0xdf, 0x34, 0xf9, 0x12, 0xba, 0xb1, 0x4a, 0xa7, 0xd8, 0xdb, 0x5a, 0xe9,
	0x97, 0x8f, 0x7a, 0xa2, 0xf8, 0x55, 0x52, 0x97, 0xb1, 0xe4, 0x6b, 0xe8, 0xad, 0x51, 0x08, 0xba,
	0x50, 0x6f, 0x21, 0xfc, 0x23, 0x6d, 0xaf, 0x8f, 0x1e, 0xa7, 0x7a, 0x53, 0x06, 0x45, 0x75, 0x82,
	0x60, 0x0a, 0x5d, 0x9b, 0x85, 0x3c, 0x83, 0x0e, 0x4b, 0x13, 0xbc, 0x33, 0x67, 0xb9, 0x18, 0x90,
	0x73, 0x68, 0xff, 0x8c, 0x3b, 0xf3, 0x7e, 0xea, 0x31, 0x58, 0x02, 0x54, 0x74, 0xf7, 0x44, 0xbd,
	0x0b, 0xa7, 0x31, 0xcb, 0x97, 0xc8, 0x6f, 0xca, 0xd8, 0x0a, 0x20, 0x17, 0x70, 0xbc, 0xa6, 0xb1,
	0xd5, 0xa2, 0x1f, 0x99, 0x11, 0x19, 0x42, 0x8b, 0x6d, 0xcd, 0x19, 0x6e, 0xb1, 0x6d, 0xf0, 0x4f,
	0x0b, 0xc8, 0xbe, 0x9f, 0x49, 0x00, 0x5d, 0x81, 0xbf, 0x6c, 0x30, 0x8d, 0xd1, 0x64, 0x2d, 0xc7,
	0xaa, 0xf8, 0xda, 0x37, 0xb6, 0xf8, 0x45, 0xee, 0x06, 0x56, 0xda, 0xce, 0x8c, 0x6d, 0x09, 0xdb,
	0xb5, 0xae, 0xd4, 0x9c, 0x52, 0x7d, 0xa4, 0x70, 0x63, 0xe5, 0x91, 0x62, 0x97, 0x2e, 0x4c, 0x3e,
	0x85, 0x0b, 0x07, 0xb2, 0xf4, 0x1d, 0x1d, 0x70, 0xcf, 0xac, 0xb2, 0x61, 0xa3, 0x1d, 0xaa, 0x14,
	0x27, 0x85, 0x0d, 0x5d, 0x5c, 0xd9, 0xd0, 0xc5, 0x6c, 0x92, 0x6e, 0x61, 0xc3, 0x7b, 0xa6, 0x83,
	0x35, 0x0c, 0x1a, 0x87, 0x58, 0x49, 0x99, 0xeb, 0xa7, 0xeb, 0xc4, 0x4a, 0x69, 0xc7, 0xba, 0xc9,
	0xb3, 0x45, 0x8a, 0xc9, 0xcc, 0xae, 0x50, 0x0a, 0x75, 0x22, 0x07, 0x55, 0xed, 0xf7, 0xb6, 0xa1,
	0xb6, 0x1d, 0x86, 0xbf, 0x7b, 0x70, 0x16, 0x61, 0x9c, 0xf1, 0xa4, 0xba, 0x3a, 0xae, 0x60, 0x18,
	0x6f, 0x38, 0xc7, 0x54, 0x1a, 0xab, 0xea, 0xbc, 0xbd, 0xe9, 0x8b, 0x07, 0x4c, 0x1c, 0x39, 0x21,
	0xe4, 0x2b, 0x38, 0xb7, 0x0d, 0xdc, 0x40, 0xc2, 0x6f, 0xe9, 0xb3, 0xf0, 0x20, 0xcd, 0x5e, 0x50,
	0x88, 0xf0, 0x8e, 0x69, 0x67, 0xce, 0x36, 0x95, 0x15, 0xad, 0x24, 0x2d, 0x96, 0x28, 0x43, 0xe7,
	0xfa, 0xb6, 0xa9, 0x19, 0xba, 0x04, 0xc8, 0x7b, 0x00, 0x79, 0x21, 0x71, 0x65, 0xea, 0x1a, 0x12,
	0xfe, 0xe9, 0xc1, 0x8b, 0x79, 0x4d, 0xb5, 0xff, 0x35, 0x9b, 0x8a, 0x56, 0x25, 0xa2, 0x8a, 0xda,
	0xf8, 0xb4, 0x02, 0xd4, 0xac, 0x64, 0x6b, 0x14, 0x92, 0xae, 0x73, 0x6d, 0xca, 0xe3, 0xa8, 0x02,
	0xc2, 0xef, 0xc0, 0xaf, 0xfb, 0x86, 0x32, 0x5e, 0xed, 0xb2, 0xb1, 0x2b, 0xef, 0xe1, 0x5d, 0xb5,
	0xf6, 0x34, 0xf8, 0xeb, 0x08, 0x9e, 0xcf, 0x75, 0x7b, 0xbc, 0xc1, 0xdd, 0x5c, 0x52, 0x89, 0x15,
	0xf3, 0xc8, 0xde, 0xbe, 0x75, 0x27, 0xd6, 0x21, 0xf2, 0xbd, 0xfa, 0xe2, 0x28, 0x6f, 0x5a, 0x9b,
	0xa1, 0x37, 0xfd, 0xa4, 0x51, 0xef, 0x83, 0xec, 0x06, 0x2f, 0xbb, 0xa9, 0x43, 0x44, 0x7e, 0xb4,
	0x37, 0x80, 0xaa, 0x50, 0xd1, 0x6a, 0x4c, 0x8f, 0x7e, 0xf5, 0x64, 0xf2, 0x2a, 0x34, 0xda, 0x23,
	0x23, 0x14, 0xde, 0x2a, 0xb0, 0x37, 0x7b, 0xad, 0xfb, 0xe9, 0x19, 0x6a, 0x1d, 0x7c, 0x9f, 0x2d,
	0xb8, 0x84, 0x61, 0xf3, 0x2d, 0x55, 0xb1, 0x98, 0xc4, 0xe2, 0xe2, 0x34, 0x82, 0x56, 0x00, 0x21,
	0x70, 0x24, 0x10, 0x13, 0x53, 0x26, 0xfd, 0x1c, 0x7c, 0xae, 0x3e, 0xf4, 0x9a, 0xc4, 0xff, 0x85,
	0xa5, 0x26, 0xc0, 0x05, 0x1c, 0x17, 0x3e, 0x31, 0xae, 0x31, 0x23, 0xd5, 0x39, 0xf2, 0xc6, 0xfd,
	0x69, 0x87, 0xe1, 0x12, 0xfc, 0x52, 0x0e, 0xf7, 0xb0, 0xbc, 0x86, 0x33, 0xd1, 0x90, 0x4a, 0xf8,
	0x9e, 0x16, 0x33, 0x7c, 0x5c, 0xcc, 0xc8, 0x0d, 0xbd, 0x7c, 0x05, 0x61, 0xc6, 0x17, 0x93, 0x5f,
	0x97, 0x4c, 0xe4, 0xc8, 0xc5, 0x4e, 0x48, 0x5c, 0x8b, 0xc9, 0x8a, 0xdd, 0xea, 0x13, 0xb3, 0x9a,
	0x08, 0xb5, 0xec, 0x72, 0x50, 0xff, 0x4e, 0x16, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x68,
	0x5f, 0x1b, 0x3c, 0x0b, 0x00, 0x00,
}
