// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WhisperTextProtocol.proto

package serialize

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignalMessage struct {
	RatchetKey           []byte   `protobuf:"bytes,1,opt,name=ratchetKey" json:"ratchetKey,omitempty"`
	Counter              *uint32  `protobuf:"varint,2,opt,name=counter" json:"counter,omitempty"`
	PreviousCounter      *uint32  `protobuf:"varint,3,opt,name=previousCounter" json:"previousCounter,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,4,opt,name=ciphertext" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalMessage) Reset()         { *m = SignalMessage{} }
func (m *SignalMessage) String() string { return proto.CompactTextString(m) }
func (*SignalMessage) ProtoMessage()    {}
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f49946562ceaf5, []int{0}
}

func (m *SignalMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalMessage.Unmarshal(m, b)
}
func (m *SignalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalMessage.Marshal(b, m, deterministic)
}
func (m *SignalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalMessage.Merge(m, src)
}
func (m *SignalMessage) XXX_Size() int {
	return xxx_messageInfo_SignalMessage.Size(m)
}
func (m *SignalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignalMessage proto.InternalMessageInfo

func (m *SignalMessage) GetRatchetKey() []byte {
	if m != nil {
		return m.RatchetKey
	}
	return nil
}

func (m *SignalMessage) GetCounter() uint32 {
	if m != nil && m.Counter != nil {
		return *m.Counter
	}
	return 0
}

func (m *SignalMessage) GetPreviousCounter() uint32 {
	if m != nil && m.PreviousCounter != nil {
		return *m.PreviousCounter
	}
	return 0
}

func (m *SignalMessage) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type PreKeySignalMessage struct {
	RegistrationId       *uint32  `protobuf:"varint,5,opt,name=registrationId" json:"registrationId,omitempty"`
	PreKeyId             *uint32  `protobuf:"varint,1,opt,name=preKeyId" json:"preKeyId,omitempty"`
	SignedPreKeyId       *uint32  `protobuf:"varint,6,opt,name=signedPreKeyId" json:"signedPreKeyId,omitempty"`
	BaseKey              []byte   `protobuf:"bytes,2,opt,name=baseKey" json:"baseKey,omitempty"`
	IdentityKey          []byte   `protobuf:"bytes,3,opt,name=identityKey" json:"identityKey,omitempty"`
	Message              []byte   `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreKeySignalMessage) Reset()         { *m = PreKeySignalMessage{} }
func (m *PreKeySignalMessage) String() string { return proto.CompactTextString(m) }
func (*PreKeySignalMessage) ProtoMessage()    {}
func (*PreKeySignalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f49946562ceaf5, []int{1}
}

func (m *PreKeySignalMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreKeySignalMessage.Unmarshal(m, b)
}
func (m *PreKeySignalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreKeySignalMessage.Marshal(b, m, deterministic)
}
func (m *PreKeySignalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreKeySignalMessage.Merge(m, src)
}
func (m *PreKeySignalMessage) XXX_Size() int {
	return xxx_messageInfo_PreKeySignalMessage.Size(m)
}
func (m *PreKeySignalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PreKeySignalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PreKeySignalMessage proto.InternalMessageInfo

func (m *PreKeySignalMessage) GetRegistrationId() uint32 {
	if m != nil && m.RegistrationId != nil {
		return *m.RegistrationId
	}
	return 0
}

func (m *PreKeySignalMessage) GetPreKeyId() uint32 {
	if m != nil && m.PreKeyId != nil {
		return *m.PreKeyId
	}
	return 0
}

func (m *PreKeySignalMessage) GetSignedPreKeyId() uint32 {
	if m != nil && m.SignedPreKeyId != nil {
		return *m.SignedPreKeyId
	}
	return 0
}

func (m *PreKeySignalMessage) GetBaseKey() []byte {
	if m != nil {
		return m.BaseKey
	}
	return nil
}

func (m *PreKeySignalMessage) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *PreKeySignalMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type KeyExchangeMessage struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BaseKey              []byte   `protobuf:"bytes,2,opt,name=baseKey" json:"baseKey,omitempty"`
	RatchetKey           []byte   `protobuf:"bytes,3,opt,name=ratchetKey" json:"ratchetKey,omitempty"`
	IdentityKey          []byte   `protobuf:"bytes,4,opt,name=identityKey" json:"identityKey,omitempty"`
	BaseKeySignature     []byte   `protobuf:"bytes,5,opt,name=baseKeySignature" json:"baseKeySignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyExchangeMessage) Reset()         { *m = KeyExchangeMessage{} }
func (m *KeyExchangeMessage) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeMessage) ProtoMessage()    {}
func (*KeyExchangeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f49946562ceaf5, []int{2}
}

func (m *KeyExchangeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeMessage.Unmarshal(m, b)
}
func (m *KeyExchangeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeMessage.Marshal(b, m, deterministic)
}
func (m *KeyExchangeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeMessage.Merge(m, src)
}
func (m *KeyExchangeMessage) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeMessage.Size(m)
}
func (m *KeyExchangeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeMessage proto.InternalMessageInfo

func (m *KeyExchangeMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *KeyExchangeMessage) GetBaseKey() []byte {
	if m != nil {
		return m.BaseKey
	}
	return nil
}

func (m *KeyExchangeMessage) GetRatchetKey() []byte {
	if m != nil {
		return m.RatchetKey
	}
	return nil
}

func (m *KeyExchangeMessage) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *KeyExchangeMessage) GetBaseKeySignature() []byte {
	if m != nil {
		return m.BaseKeySignature
	}
	return nil
}

type SenderKeyMessage struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Iteration            *uint32  `protobuf:"varint,2,opt,name=iteration" json:"iteration,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,3,opt,name=ciphertext" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SenderKeyMessage) Reset()         { *m = SenderKeyMessage{} }
func (m *SenderKeyMessage) String() string { return proto.CompactTextString(m) }
func (*SenderKeyMessage) ProtoMessage()    {}
func (*SenderKeyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f49946562ceaf5, []int{3}
}

func (m *SenderKeyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderKeyMessage.Unmarshal(m, b)
}
func (m *SenderKeyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderKeyMessage.Marshal(b, m, deterministic)
}
func (m *SenderKeyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderKeyMessage.Merge(m, src)
}
func (m *SenderKeyMessage) XXX_Size() int {
	return xxx_messageInfo_SenderKeyMessage.Size(m)
}
func (m *SenderKeyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderKeyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SenderKeyMessage proto.InternalMessageInfo

func (m *SenderKeyMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SenderKeyMessage) GetIteration() uint32 {
	if m != nil && m.Iteration != nil {
		return *m.Iteration
	}
	return 0
}

func (m *SenderKeyMessage) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type SenderKeyDistributionMessage struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Iteration            *uint32  `protobuf:"varint,2,opt,name=iteration" json:"iteration,omitempty"`
	ChainKey             []byte   `protobuf:"bytes,3,opt,name=chainKey" json:"chainKey,omitempty"`
	SigningKey           []byte   `protobuf:"bytes,4,opt,name=signingKey" json:"signingKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SenderKeyDistributionMessage) Reset()         { *m = SenderKeyDistributionMessage{} }
func (m *SenderKeyDistributionMessage) String() string { return proto.CompactTextString(m) }
func (*SenderKeyDistributionMessage) ProtoMessage()    {}
func (*SenderKeyDistributionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f49946562ceaf5, []int{4}
}

func (m *SenderKeyDistributionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderKeyDistributionMessage.Unmarshal(m, b)
}
func (m *SenderKeyDistributionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderKeyDistributionMessage.Marshal(b, m, deterministic)
}
func (m *SenderKeyDistributionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderKeyDistributionMessage.Merge(m, src)
}
func (m *SenderKeyDistributionMessage) XXX_Size() int {
	return xxx_messageInfo_SenderKeyDistributionMessage.Size(m)
}
func (m *SenderKeyDistributionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderKeyDistributionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SenderKeyDistributionMessage proto.InternalMessageInfo

func (m *SenderKeyDistributionMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SenderKeyDistributionMessage) GetIteration() uint32 {
	if m != nil && m.Iteration != nil {
		return *m.Iteration
	}
	return 0
}

func (m *SenderKeyDistributionMessage) GetChainKey() []byte {
	if m != nil {
		return m.ChainKey
	}
	return nil
}

func (m *SenderKeyDistributionMessage) GetSigningKey() []byte {
	if m != nil {
		return m.SigningKey
	}
	return nil
}

type DeviceConsistencyCodeMessage struct {
	Generation           *uint32  `protobuf:"varint,1,opt,name=generation" json:"generation,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceConsistencyCodeMessage) Reset()         { *m = DeviceConsistencyCodeMessage{} }
func (m *DeviceConsistencyCodeMessage) String() string { return proto.CompactTextString(m) }
func (*DeviceConsistencyCodeMessage) ProtoMessage()    {}
func (*DeviceConsistencyCodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f49946562ceaf5, []int{5}
}

func (m *DeviceConsistencyCodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceConsistencyCodeMessage.Unmarshal(m, b)
}
func (m *DeviceConsistencyCodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceConsistencyCodeMessage.Marshal(b, m, deterministic)
}
func (m *DeviceConsistencyCodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConsistencyCodeMessage.Merge(m, src)
}
func (m *DeviceConsistencyCodeMessage) XXX_Size() int {
	return xxx_messageInfo_DeviceConsistencyCodeMessage.Size(m)
}
func (m *DeviceConsistencyCodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConsistencyCodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConsistencyCodeMessage proto.InternalMessageInfo

func (m *DeviceConsistencyCodeMessage) GetGeneration() uint32 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *DeviceConsistencyCodeMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*SignalMessage)(nil), "serialize.SignalMessage")
	proto.RegisterType((*PreKeySignalMessage)(nil), "serialize.PreKeySignalMessage")
	proto.RegisterType((*KeyExchangeMessage)(nil), "serialize.KeyExchangeMessage")
	proto.RegisterType((*SenderKeyMessage)(nil), "serialize.SenderKeyMessage")
	proto.RegisterType((*SenderKeyDistributionMessage)(nil), "serialize.SenderKeyDistributionMessage")
	proto.RegisterType((*DeviceConsistencyCodeMessage)(nil), "serialize.DeviceConsistencyCodeMessage")
}

func init() { proto.RegisterFile("WhisperTextProtocol.proto", fileDescriptor_d7f49946562ceaf5) }

var fileDescriptor_d7f49946562ceaf5 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xda, 0x05, 0x76, 0x87, 0x76, 0x59, 0x85, 0x4b, 0x58, 0x55, 0xa8, 0x8a, 0x04, 0xaa,
	0x38, 0xf4, 0xc6, 0x0f, 0x6c, 0x97, 0xc3, 0xaa, 0x42, 0xaa, 0xb2, 0x48, 0x5c, 0x38, 0xe0, 0x3a,
	0x23, 0x67, 0xa4, 0xac, 0x1d, 0xd9, 0xee, 0xd2, 0xf0, 0x05, 0xdc, 0xf9, 0x0d, 0xfe, 0x87, 0xdf,
	0x41, 0xb6, 0x93, 0x26, 0x6d, 0x04, 0x07, 0x6e, 0x99, 0x97, 0xb1, 0xdf, 0x9b, 0xf7, 0x3c, 0xf0,
	0xea, 0x73, 0x41, 0xa6, 0x42, 0xfd, 0x09, 0xf7, 0x76, 0xa3, 0x95, 0x55, 0x5c, 0x95, 0xcb, 0xca,
	0x7d, 0xc4, 0x17, 0x06, 0x35, 0xb1, 0x92, 0xbe, 0x63, 0xfa, 0x33, 0x82, 0xe9, 0x3d, 0x09, 0xc9,
	0xca, 0x8f, 0x68, 0x0c, 0x13, 0x18, 0xbf, 0x06, 0xd0, 0xcc, 0xf2, 0x02, 0xed, 0x1a, 0xeb, 0x24,
	0x9a, 0x47, 0x8b, 0x49, 0xd6, 0x43, 0xe2, 0x04, 0x9e, 0x71, 0xb5, 0x93, 0x16, 0x75, 0x32, 0x9a,
	0x47, 0x8b, 0x69, 0xd6, 0x96, 0xf1, 0x02, 0x5e, 0x54, 0x1a, 0x1f, 0x49, 0xed, 0xcc, 0xaa, 0xe9,
	0x18, 0xfb, 0x8e, 0x53, 0xd8, 0x71, 0x70, 0xaa, 0x0a, 0xd4, 0x16, 0xf7, 0x36, 0x39, 0x0b, 0x1c,
	0x1d, 0x92, 0xfe, 0x8e, 0xe0, 0xe5, 0x46, 0xe3, 0x1a, 0xeb, 0x63, 0x6d, 0x6f, 0xe1, 0x52, 0xa3,
	0x20, 0x63, 0x35, 0xb3, 0xa4, 0xe4, 0x5d, 0x9e, 0x3c, 0xf1, 0x04, 0x27, 0x68, 0x7c, 0x0d, 0xe7,
	0x95, 0x3f, 0x7e, 0x97, 0xfb, 0x09, 0xa6, 0xd9, 0xa1, 0x76, 0x77, 0x18, 0x12, 0x12, 0xf3, 0x4d,
	0xdb, 0xf1, 0x34, 0xdc, 0x71, 0x8c, 0xba, 0x39, 0xb7, 0xcc, 0xb8, 0xc2, 0xcf, 0x39, 0xc9, 0xda,
	0x32, 0x9e, 0xc3, 0x73, 0xca, 0x51, 0x5a, 0xb2, 0xb5, 0xfb, 0x3b, 0xf6, 0x7f, 0xfb, 0x90, 0x3b,
	0xfb, 0x10, 0x24, 0x37, 0xc3, 0xb5, 0x65, 0xfa, 0x2b, 0x82, 0x78, 0x8d, 0xf5, 0x87, 0x3d, 0x2f,
	0x98, 0x14, 0xd8, 0x0e, 0x76, 0x09, 0x23, 0x6a, 0xa5, 0x8e, 0xe8, 0x5f, 0xe4, 0xc7, 0xf1, 0x8c,
	0x07, 0xf1, 0x9c, 0x88, 0x3b, 0x1b, 0x8a, 0x7b, 0x07, 0x57, 0xcd, 0x65, 0xde, 0x5c, 0xbb, 0xd3,
	0xe8, 0x6d, 0x9c, 0x64, 0x03, 0x3c, 0xfd, 0x0a, 0x57, 0xf7, 0x28, 0x73, 0xd4, 0x6b, 0xac, 0xff,
	0xa6, 0x75, 0x06, 0x17, 0x64, 0x31, 0x78, 0xdf, 0x3c, 0x89, 0x0e, 0x38, 0x89, 0x7a, 0x3c, 0x88,
	0xfa, 0x47, 0x04, 0xb3, 0x03, 0xc5, 0xad, 0x0b, 0x91, 0xb6, 0x3b, 0x77, 0xf2, 0xff, 0xe8, 0xae,
	0xe1, 0x9c, 0x17, 0x8c, 0x64, 0x67, 0xce, 0xa1, 0x76, 0x52, 0x5c, 0xc6, 0x24, 0x45, 0xe7, 0x4c,
	0x0f, 0x49, 0xbf, 0xc0, 0xec, 0x16, 0x1f, 0x89, 0xe3, 0x4a, 0x49, 0x43, 0xc6, 0xa2, 0xe4, 0xf5,
	0x4a, 0xe5, 0xd8, 0xdb, 0x0c, 0x81, 0xb2, 0xa5, 0x0e, 0x8a, 0x7a, 0x88, 0x53, 0x66, 0x0e, 0x8e,
	0x86, 0xd8, 0x3a, 0xe0, 0xe6, 0x3d, 0xbc, 0x51, 0x5a, 0x2c, 0xbf, 0x85, 0xad, 0x34, 0xb5, 0xb1,
	0xf8, 0x60, 0x96, 0x25, 0x6d, 0x7d, 0x4b, 0xb3, 0x9a, 0x5c, 0x95, 0x37, 0x93, 0xf0, 0xe6, 0xfd,
	0xce, 0x9a, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x25, 0x04, 0x6c, 0xc7, 0x03, 0x00, 0x00,
}
